### ISSUE TITLE
checkbox_submit not working

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#70]
In GitLab by @bzk60 on Jul 17, 2018, 16:31

stemming from #64

EDIT 7/23/18:

this is now a RoR/Blacklight issue. perhaps a route problem or something to do with how session info is handled.

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 18, 2018, 07:55

changed the description

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 18, 2018, 16:28

added ~938 label

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 19, 2018, 10:46

assigned to @cdm32

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 20, 2018, 08:41

removed ~938 label

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 20, 2018, 13:44

added ~938 label

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 20, 2018, 14:36

![2018-07-20_1435](/uploads/26d640eb5e792fe535920b1f23552794/2018-07-20_1435.png)

when just checkbox_submit.js is loaded: no errors  
when checkbox_submit.js and bookmark_tolggle.js are loaded this happens with this error:   

![Screen_Shot_2018-07-20_at_2.36.32_PM](/uploads/b3c8849a5f60f15f294fb112a5c1f628/Screen_Shot_2018-07-20_at_2.36.32_PM.png)

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 20, 2018, 14:41

aha similar error that is for the modal

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 20, 2018, 14:43

bet it's a deprecation in jquery, checking now

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 20, 2018, 14:47

yup:

https://api.jquery.com/size/

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 20, 2018, 14:53

using `length` instead of `size()` works, but I am seeing this when I re-check an unchecked box in my bookmarks

![Screen_Shot_2018-07-20_at_2.53.21_PM](/uploads/f462f7124f5ee3e5d96d26eec5d127fb/Screen_Shot_2018-07-20_at_2.53.21_PM.png)

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 20, 2018, 15:27

so, fix is https://github.com/projectblacklight/blacklight/pull/1947

this fix also fixes #66 

in the meantime.... guess we can use the `cdmo` fork for our front end

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 20, 2018, 15:33

mentioned in commit 09d622bbfc7355917b188490778667131d4ced00

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 20, 2018, 16:00

yes good idea!

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 23, 2018, 10:07

the problem with this issue is that there's an error on uncheck => check. you get the error here: https://git.psu.edu/i-tech/psulib_blacklight/issues/70#note_104185

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 23, 2018, 10:16

Dumpe of `xhr.responseText`:

```
// "ActionController::InvalidAuthenticityToken in BookmarksController#update↵
// ↵
// ActionController::InvalidAuthenticityToken↵
// Extracted source (around line #195):↵
// ↵
// #193 ↵
// #194         def handle_unverified_request↵
// *195           raise ActionController::InvalidAuthenticityToken↵
// #196         end↵
// #197       end↵
// #198     end↵
// ↵
// Extracted source (around line #227):↵
// ↵
// #225 ↵
// #226       def handle_unverified_request # :doc:↵
// *227         forgery_protection_strategy.new(self).handle_unverified_request↵
// #228       end↵
// #229 ↵
// #230       #:nodoc:↵
// ↵
// Extracted source (around line #255):↵
// ↵
// #253       # clear run strategies and remove cached variables.↵
// #254       def handle_unverified_request↵
// *255         super # call the default behaviour which resets/nullifies/raises↵
// #256         request.env["devise.skip_storage"] = true↵
// #257         sign_out_all_scopes(false)↵
// #258       end↵
// ↵
// ↵
// Rails.root: /Users/cdm32/Projects/psulib_blacklight↵
// ↵
// Framework Trace↵
// actionpack (5.1.6) lib/action_controller/metal/request_forgery_protection.rb:195:in `handle_unverified_request'↵
// actionpack (5.1.6) lib/action_controller/metal/request_forgery_protection.rb:227:in `handle_unverified_request'↵
// devise (4.4.3) lib/devise/controllers/helpers.rb:255:in `handle_unverified_request'↵
// actionpack (5.1.6) lib/action_controller/metal/request_forgery_protection.rb:222:in `verify_authenticity_token'↵
// activesupport (5.1.6) lib/active_support/callbacks.rb:413:in `block in make_lambda'↵
// activesupport (5.1.6) lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'↵
// actionpack (5.1.6) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'↵
// activesupport (5.1.6) lib/active_support/callbacks.rb:198:in `block in halting'↵
// activesupport (5.1.6) lib/active_support/callbacks.rb:507:in `block in invoke_before'↵
// activesupport (5.1.6) lib/active_support/callbacks.rb:507:in `each'↵
// activesupport (5.1.6) lib/active_support/callbacks.rb:507:in `invoke_before'↵
// activesupport (5.1.6) lib/active_support/callbacks.rb:130:in `run_callbacks'↵
// actionpack (5.1.6) lib/abstract_controller/callbacks.rb:19:in `process_action'↵
// actionpack (5.1.6) lib/action_controller/metal/rescue.rb:20:in `process_action'↵
// actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'↵
// activesupport (5.1.6) lib/active_support/notifications.rb:166:in `block in instrument'↵
// activesupport (5.1.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'↵
// activesupport (5.1.6) lib/active_support/notifications.rb:166:in `instrument'↵
// actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'↵
// actionpack (5.1.6) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'↵
// activerecord (5.1.6) lib/active_record/railties/controller_runtime.rb:22:in `process_action'↵
// actionpack (5.1.6) lib/abstract_controller/base.rb:124:in `process'↵
// actionview (5.1.6) lib/action_view/rendering.rb:30:in `process'↵
// actionpack (5.1.6) lib/action_controller/metal.rb:189:in `dispatch'↵
// actionpack (5.1.6) lib/action_controller/metal.rb:253:in `dispatch'↵
// actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'↵
// actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:31:in `serve'↵
// actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'↵
// actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `each'↵
// actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `serve'↵
// actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in `call'↵
// warden (1.2.7) lib/warden/manager.rb:36:in `block in call'↵
// warden (1.2.7) lib/warden/manager.rb:35:in `catch'↵
// warden (1.2.7) lib/warden/manager.rb:35:in `call'↵
// rack (2.0.5) lib/rack/etag.rb:25:in `call'↵
// rack (2.0.5) lib/rack/conditional_get.rb:38:in `call'↵
// rack (2.0.5) lib/rack/head.rb:12:in `call'↵
// rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'↵
// rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'↵
// actionpack (5.1.6) lib/action_dispatch/middleware/cookies.rb:613:in `call'↵
// activerecord (5.1.6) lib/active_record/migration.rb:556:in `call'↵
// actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'↵
// activesupport (5.1.6) lib/active_support/callbacks.rb:97:in `run_callbacks'↵
// actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:24:in `call'↵
// actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'↵
// actionpack (5.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'↵
// web-console (3.6.2) lib/web_console/middleware.rb:135:in `call_app'↵
// web-console (3.6.2) lib/web_console/middleware.rb:30:in `block in call'↵
// web-console (3.6.2) lib/web_console/middleware.rb:20:in `catch'↵
// web-console (3.6.2) lib/web_console/middleware.rb:20:in `call'↵
// actionpack (5.1.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'↵
// railties (5.1.6) lib/rails/rack/logger.rb:36:in `call_app'↵
// railties (5.1.6) lib/rails/rack/logger.rb:24:in `block in call'↵
// activesupport (5.1.6) lib/active_support/tagged_logging.rb:69…l/instrumentation.rb:32:in `block in process_action'↵
// activesupport (5.1.6) lib/active_support/notifications.rb:166:in `block in instrument'↵
// activesupport (5.1.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'↵
// activesupport (5.1.6) lib/active_support/notifications.rb:166:in `instrument'↵
// actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'↵
// actionpack (5.1.6) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'↵
// activerecord (5.1.6) lib/active_record/railties/controller_runtime.rb:22:in `process_action'↵
// actionpack (5.1.6) lib/abstract_controller/base.rb:124:in `process'↵
// actionview (5.1.6) lib/action_view/rendering.rb:30:in `process'↵
// actionpack (5.1.6) lib/action_controller/metal.rb:189:in `dispatch'↵
// actionpack (5.1.6) lib/action_controller/metal.rb:253:in `dispatch'↵
// actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'↵
// actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:31:in `serve'↵
// actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'↵
// actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `each'↵
// actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `serve'↵
// actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in `call'↵
// warden (1.2.7) lib/warden/manager.rb:36:in `block in call'↵
// warden (1.2.7) lib/warden/manager.rb:35:in `catch'↵
// warden (1.2.7) lib/warden/manager.rb:35:in `call'↵
// rack (2.0.5) lib/rack/etag.rb:25:in `call'↵
// rack (2.0.5) lib/rack/conditional_get.rb:38:in `call'↵
// rack (2.0.5) lib/rack/head.rb:12:in `call'↵
// rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'↵
// rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'↵
// actionpack (5.1.6) lib/action_dispatch/middleware/cookies.rb:613:in `call'↵
// activerecord (5.1.6) lib/active_record/migration.rb:556:in `call'↵
// actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'↵
// activesupport (5.1.6) lib/active_support/callbacks.rb:97:in `run_callbacks'↵
// actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:24:in `call'↵
// actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'↵
// actionpack (5.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'↵
// web-console (3.6.2) lib/web_console/middleware.rb:135:in `call_app'↵
// web-console (3.6.2) lib/web_console/middleware.rb:30:in `block in call'↵
// web-console (3.6.2) lib/web_console/middleware.rb:20:in `catch'↵
// web-console (3.6.2) lib/web_console/middleware.rb:20:in `call'↵
// actionpack (5.1.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'↵
// railties (5.1.6) lib/rails/rack/logger.rb:36:in `call_app'↵
// railties (5.1.6) lib/rails/rack/logger.rb:24:in `block in call'↵
// activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `block in tagged'↵
// activesupport (5.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'↵
// activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `tagged'↵
// railties (5.1.6) lib/rails/rack/logger.rb:24:in `call'↵
// sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'↵
// actionpack (5.1.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'↵
// actionpack (5.1.6) lib/action_dispatch/middleware/request_id.rb:25:in `call'↵
// rack (2.0.5) lib/rack/method_override.rb:22:in `call'↵
// rack (2.0.5) lib/rack/runtime.rb:22:in `call'↵
// activesupport (5.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'↵
// actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'↵
// actionpack (5.1.6) lib/action_dispatch/middleware/static.rb:125:in `call'↵
// rack (2.0.5) lib/rack/sendfile.rb:111:in `call'↵
// webpacker (3.5.5) lib/webpacker/dev_server_proxy.rb:22:in `perform_request'↵
// rack-proxy (0.6.4) lib/rack/proxy.rb:57:in `call'↵
// railties (5.1.6) lib/rails/engine.rb:522:in `call'↵
// puma (3.12.0) lib/puma/configuration.rb:225:in `call'↵
// puma (3.12.0) lib/puma/server.rb:658:in `handle_request'↵
// puma (3.12.0) lib/puma/server.rb:472:in `process_client'↵
// puma (3.12.0) lib/puma/server.rb:332:in `block in run'↵
// puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'↵
// ↵
// ↵
// ↵
// Request parameters↵
// {"utf8"=>"✓",↵
// "_method"=>"put",↵
// "authenticity_token"=>"ZhWCUre6D08DLnGxuXoabfr2N29tE6KkT6qEuuGNntcHcs01om5GPVvAuuisUyXstaUUExRoK+BsgjDEqa9OrA==",↵
// "id"=>"22090269"}↵
// ↵
// Session dump↵
// _csrf_token: "zlunkBKktlyt8e2hgkZr2H2F3Um5hBzmNFFPOJaIfIk="↵
// guest_user_id: "guest_RvHo6ZfzuxGRb1nzgx45_1532100668_1@example.com"↵
// history: [3, 2, 1, 5, 4, 3, 2, 1]↵
// search: {"id"=>nil, "counter"=>"1", "per_page"=>nil, "total"=>1}↵
// session_id: "cc7024dbe65852621602c741e0db1f81"↵
// ↵
// Env dump↵
// GATEWAY_INTERFACE: "CGI/1.2"↵
// HTTP_ACCEPT: "application/json, text/javascript, */*; q=0.01"↵
// HTTP_ACCEPT_ENCODING: "gzip, deflate, br"↵
// HTTP_ACCEPT_LANGUAGE: "en,en-US;q=0.9"↵
// HTTP_CACHE_CONTROL: "no-cache"↵
// HTTP_ORIGIN: "http://localhost:3000"↵
// HTTP_PRAGMA: "no-cache"↵
// HTTP_VERSION: "HTTP/1.1"↵
// ORIGINAL_SCRIPT_NAME: ""↵
// REMOTE_ADDR: "127.0.0.1"↵
// SERVER_NAME: "localhost"↵
// SERVER_PROTOCOL: "HTTP/1.1"↵
// ↵
// Response headers↵
// None↵
// ↵
// "
```

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 23, 2018, 10:26

this is not broken on the demo blacklight, fwiw

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 23, 2018, 12:08

closed via commit 09d622bbfc7355917b188490778667131d4ced00

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 23, 2018, 12:08

closed via commit bc5220150319669ce4b400aa7d3bbcd6239b3fcb

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 23, 2018, 12:08

closed via merge request !5

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Jul 23, 2018, 12:16

removed ~938 label

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 23, 2018, 12:23

this is no longer a pure js/frontend problem. It involves the backend/ruby. So I'm going to throw to the back log __for now__ so that I can work on capistrano stuff

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Jul 23, 2018, 12:24

changed the description

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Aug 29, 2018, 10:28

mentioned in commit bc5220150319669ce4b400aa7d3bbcd6239b3fcb
