### ISSUE TITLE
Dev environment warnings

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_blacklight#81]
In GitLab by @cdm32 on Jul 23, 2018, 12:27

```
➜  psulib_blacklight git:(blv7.0) ✗ rails c
/Users/cdm32/.rbenv/versions/2.5.1/lib/ruby/2.5.0/fileutils.rb:90: warning: already initialized constant FileUtils::VERSION
/Users/cdm32/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:92: warning: previous definition of VERSION was here
/Users/cdm32/.rbenv/versions/2.5.1/lib/ruby/2.5.0/fileutils.rb:1188: warning: already initialized constant FileUtils::Entry_::S_IF_DOOR
/Users/cdm32/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1267: warning: previous definition of S_IF_DOOR was here
/Users/cdm32/.rbenv/versions/2.5.1/lib/ruby/2.5.0/fileutils.rb:1446: warning: already initialized constant FileUtils::Entry_::DIRECTORY_TERM
/Users/cdm32/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1541: warning: previous definition of DIRECTORY_TERM was here
/Users/cdm32/.rbenv/versions/2.5.1/lib/ruby/2.5.0/fileutils.rb:1448: warning: already initialized constant FileUtils::Entry_::SYSCASE
/Users/cdm32/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1543: warning: previous definition of SYSCASE was here
/Users/cdm32/.rbenv/versions/2.5.1/lib/ruby/2.5.0/fileutils.rb:1501: warning: already initialized constant FileUtils::OPT_TABLE
/Users/cdm32/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1596: warning: previous definition of OPT_TABLE was here
/Users/cdm32/.rbenv/versions/2.5.1/lib/ruby/2.5.0/fileutils.rb:1555: warning: already initialized constant FileUtils::LOW_METHODS
/Users/cdm32/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1650: warning: previous definition of LOW_METHODS was here
/Users/cdm32/.rbenv/versions/2.5.1/lib/ruby/2.5.0/fileutils.rb:1562: warning: already initialized constant FileUtils::METHODS
/Users/cdm32/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fileutils-1.1.0/lib/fileutils.rb:1657: warning: previous definition of METHODS was here
Running via Spring preloader in process 34906
Loading development environment (Rails 5.1.6)
No entry for terminal type "/versions/2.5.1/bin:/usr/local/Cellar/rbenv/1.1.1/libexec:/Users/cdm32/.rbenv/shims:/usr/local/opt/openssl/bin:/Users/cdm32/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin";
using dumb terminal settings.
```

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 5, 2018, 13:32

related: https://github.com/ruby/fileutils/issues/22

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 17, 2018, 16:23

added ~938 label

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 17, 2018, 16:31

The problem has been solved, I tried a few things, including removing fileutils and adding it again. 
 When I did that I got a new error:

```
Traceback (most recent call last):
	5: from bin/rails:3:in `<main>'
	4: from bin/rails:3:in `load'
	3: from /Users/cdm32/Desktop/blah/bin/spring:8:in `<top (required)>'
	2: from /Users/cdm32/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	1: from /Users/cdm32/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
/Users/cdm32/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- bundler (LoadError)
```

though I'm not 100% sure which step solved it, here's what I did next:

`brew update`  
`gem update --system`  

I think it was probably the last piece, which does the following: `Update the RubyGems system software`. I now have gem v. 2.7.7 installed.

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 17, 2018, 16:31

closed

**Comment by banukutlu** [comment]
In GitLab by @bzk60 on Sep 21, 2018, 09:23

removed ~938 label

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 21, 2018, 10:40

Ok, after some more require issues with failed loads from bootsnap I finally got it solved: clear the cache (just like Drupal 😅) for bootsnap:

- go to the project home, then cd into tmp/cache
- delete `bootsnap-load-path-cache` and `bootsnap-compile-cache`

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 21, 2018, 10:44

See https://github.com/Shopify/bootsnap/issues/73
