### ISSUE TITLE
Rescue 503 errors and other more nicely

### ISSUE THREAD

**Issue by awead** [psu-libraries/psulib_blacklight#853]
In QA, if Solr throws a 503 "Service Unavailable" we get a big blank page. This is happening with subject browse, but it could be any solr or server error:

```
catalog Error: {                                                                                                                                           │
│ catalog   "responseHeader":{                                                                                                                               │
│ catalog     "status":503,                                                                                                                                  │
│ catalog     "QTime":1,                                                                                                                                     │
│ catalog     "params":{                                                                                                                                     │
│ catalog       "facet.limit":"11",                                                                                                                          │
│ catalog       "facet.field":"subject_browse_facet",                                                                                                        │
│ catalog       "rows":"0",                                                                                                                                  │
│ catalog       "facet":"true",                                                                                                                              │
│ catalog       "wt":"json",                                                                                                                                 │
│ catalog       "facet.offset":"80",                                                                                                                         │
│ catalog URI: http://psulib-blackight:ebd366cb763fe1b53531cb2f93cc94734ca205eadc1af4b8a8@catalog-qa-solrcloud-common/solr/psulib-blacklight/select?wt=json& │
│ catalog Backtrace: /app/vendor/bundle/ruby/2.7.0/gems/rsolr-2.3.0/lib/rsolr/client.rb:206:in `rescue in execute'                                           │
│ catalog /app/vendor/bundle/ruby/2.7.0/gems/rsolr-2.3.0/lib/rsolr/client.rb:196:in `execute'                                                                │
│ catalog /app/vendor/bundle/ruby/2.7.0/gems/rsolr-2.3.0/lib/rsolr/client.rb:191:in `send_and_receive'                                                       │
│ catalog (eval):2:in `get'                                                                                                                                  │
│ catalog /app/app/services/subject_list.rb:46:in `facet_query'                                                                                              │
│ catalog /app/app/services/subject_list.rb:33:in `items'                                                                                                    │
│ catalog /app/app/services/subject_list.rb:26:in `last_page?'                                                                                               │
│ catalog /app/app/services/subject_list.rb:20:in `entries'                                                                                                  │
│ catalog /app/app/services/subject_list.rb:11:in `empty?'                                                                                                   │
│ catalog /app/app/views/browse/subjects.html.erb:5:in `_app_views_browse_subjects_html_erb__2946663233354378461_29400'                                      │
│ catalog /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.4/lib/action_view/base.rb:274:in `_run'' duration=8.84 view=0.00 db=0.00 params={"length"=>"10", │
│ catalog F, [2021-09-01T11:06:58.407072 #13] FATAL -- : [b80456ef97568728cdd0e501bcfeca53]                                                                  │
│ catalog [b80456ef97568728cdd0e501bcfeca53] ActionView::Template::Error (RSolr::Error::Http - 503 Service Unavailable    
```

 It'd be nicer to show something else.

## WDLL

Show a standard "server error" page when encountering unrecoverable problems

## Questions

* does this currently happen in prod?
* what does the page look like?
* are we recovering from other requests? 5xx? non-html formats, i.e. json?
* what happens with ajax and .json errors?

**Comment by banukutlu** [comment]
> ## Questions
> * does this currently happen in prod?
No as far as I can recall.
> * what does the page look like?
> * are we recovering from other requests? 5xx? non-html formats, i.e. json?
There is a error controller to catch and display an error page for 404 and 500s 
eg. https://catalog.libraries.psu.edu/catalog/wrong_key
> * what happens with ajax and .json errors?

**Comment by awead** [comment]
We did the same thing in SS:

https://github.com/psu-libraries/scholarsphere/commit/1f84da174b2a55468ebd1d6d5a033f71aa8aad54

But I think your missing: `config.exceptions_app = routes` in your config/application.rb.

We can do some more testing in qa.
