### ISSUE TITLE
NoMethodError in SolrManager

### ISSUE THREAD

**Issue by awead** [psu-libraries/psulib_blacklight#866]
Deploying QA is currently broken with this error:

```
NoMethodError: undefined method `include?' for nil:NilClass                                                                                        │
│ catalog /app/lib/psulib_blacklight/solr_manager.rb:98:in `configset_exists?'                                                                               │
│ catalog /app/lib/psulib_blacklight/solr_manager.rb:17:in `initialize'                                                                                      │
│ catalog /app/lib/tasks/solr.rake:8:in `new'                                                                                                                │
│ catalog /app/lib/tasks/solr.rake:8:in `solr_manager'                                                                                                       │
│ catalog /app/lib/tasks/solr.rake:16:in `block (2 levels) in <top (required)>'                                                                              │
│ catalog /app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.4/exe/rake:27:in `<top (required)>'                                                                   │
│ catalog /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:63:in `load'                                                                         │
│ catalog /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:63:in `kernel_load'                                                                  │
│ catalog /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/cli/exec.rb:28:in `run'                                                                          │
│ catalog /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/cli.rb:475:in `exec'                                                                             │
│ catalog /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'                                                      │
│ catalog /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'                                       │
│ catalog /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'                                                        │
│ catalog /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/cli.rb:31:in `dispatch'                                                                          │
│ catalog /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'                                                      │
│ catalog /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/cli.rb:25:in `start'                                                                             │
│ catalog /usr/local/bundle/gems/bundler-2.2.24/exe/bundle:49:in `block in <top (required)>'                                                                 │
│ catalog /usr/local/bundle/gems/bundler-2.2.24/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'                                                 │
│ catalog /usr/local/bundle/gems/bundler-2.2.24/exe/bundle:37:in `<top (required)>'                                                                          │
│ catalog /usr/local/bundle/bin/bundle:23:in `load'                                                                                                          │
│ catalog /usr/local/bundle/bin/bundle:23:in `<main>'                                                                                                        │
│ catalog Tasks: TOP => solr:initialize_collection                                                                                                           │
│ catalog (See full trace by running task with --trace)               
```

**Comment by whereismyjetpack** [comment]
This happens when solr wants to deadlock itself. we can mitigate this by setting livenessprobes, but when they are unreliable they cause even more problems. I think this happens in qa more than others because of the version of solr, i think 8.x handles this much better (i could be wrong. i haven't seen it as much with the others) When this happens again, please let me know so i can do some tracing and see if we can auto-mitigate it.

**Comment by awead** [comment]
Would rescuing the error and doing something help?

**Comment by whereismyjetpack** [comment]
in this case it won't since the solr service is completely messed up. the resolution would be to fix solr when it breaks automatically without attempting to fix it during an index when restarting the containers would cause a cascading failure type situation

**Comment by awead** [comment]
If we did rescue and continue, then the rails app should start, albeit with a non-functioning solr, correct? Currently, this breaks the boot up process so that you couldn't even shell into the pod. Hypothetically, if solr was broken you could get a console session going and potentially use SolrManager to fix things?

**Comment by whereismyjetpack** [comment]
Oh yes, if solrmanager fails we should start up.. might give us a place to easily trouble shoot
